name: Tests

on:
  push:
    branches: [main, test]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'test'
      - run: cd test && npm install
      - run: cd test && npm test